# Generated by Django 5.0.2 on 2024-06-28 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
